"""empty message

Revision ID: 875138d393a2
Revises: 4aceeabda5b6
Create Date: 2023-08-25 19:34:32.424015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875138d393a2'
down_revision: Union[str, None] = '4aceeabda5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('date_create', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'date_create')
    # ### end Alembic commands ###
